### ISSUE TITLE
exception in ObjCIdentifierFromManagedIdentifier() while generating bindings involving nested enums

### ISSUE THREAD

**Issue by Numpsy** [ThesaurusSoftware/Dubrovnik#10]
While trying to generate some bindings using the latest BPUKM-1718 branch, I get an exception from ObjCIdentifierFromManagedIdentifier() due to managedIdentifier having a '/' in it.

A simple repro seems to be possible using this:

```
namespace TestAssembly
{
    public class TestClass
    {
        public enum TestEnum
        {
            item1
        }

        public void testIt(TestEnum tw)
        {

        }

        public void testIt(int tw)
        {

        }
    }
}
```

Not sure if this is just a case that needs to be handled in the list of replaces in the function, or if it's something else? (actually, it looks like the generator might have inserted the '/' in place of a '+' in WriteFacetAsMethod() ?)

**Comment by mugginsoft** [comment]
I think it is the enum that is causing the issue this commit is looks relevant:

https://github.com/ThesaurusSoftware/Dubrovnik/commit/715b3778b00b039b48f1d97fc6e5b46738c0811f

I don't have time to dig into this one in detail right now but try this:

in CodeFacet. ObjCIdentifierFromManagedIdentifier

after
identifier.Replace("+", "__"); // nested classes
add
identifier.Replace("/", "__"); // nested classes

The embedded method calling API has its own syntax for representing embedded types in signatures - God knows why.

Let me know how you get on.

**Comment by KosmicTask** [comment]
Try pulling the head of  BPUKM17-18 now and see how you get on.

**Comment by Numpsy** [comment]
ok, thanks, i'll have a look later.

**Comment by Numpsy** [comment]
Well, the code generator doesn't fail any more :-) (haven't had change to try much more of a test than that).

**Comment by KosmicTask** [comment]
I' close this as I have recently improved nested type handling, which was broken in some places.
