### ISSUE TITLE
#include "System_IntPtr.h" ?

### ISSUE THREAD

**Issue by Numpsy** [ThesaurusSoftware/Dubrovnik#11]
Pretty trivial this, but: any reason why System_IntPtr.m includes System_IntPtr.h rather than importing it? (I was tinkering with the prefix header, and noticed it after getting duplicate definition warnings from the header being included twice.).

https://github.com/ThesaurusSoftware/Dubrovnik/blob/BPUKM-1718/Mono.mscorlib/Mono.mscorlib/Manual%20bindings/System_IntPtr.m#L1

https://github.com/ThesaurusSoftware/Dubrovnik/blob/BPUKM-1718/Mono.mscorlib/Mono.mscorlib/Include/ManualBindings.h#L28

**Comment by KosmicTask** [comment]
Those should be `#import` not `#include`.

**Comment by Numpsy** [comment]
https://github.com/ThesaurusSoftware/Dubrovnik/pull/13
