### ISSUE TITLE
extending IEnumerable and friends

### ISSUE THREAD

**Issue by Numpsy** [ThesaurusSoftware/Dubrovnik#12]
I've been having a look at using IEnumerable/IEnumerator etc to help expose some managed collections to Swift, which means generating extra bindings etc.

Any objections to some pull requests to add some extra bits? (e.g. definitions for IEnumerator, accessor functions on IEnumerable) ?

Thanks.

**Comment by KosmicTask** [comment]
Sure. One of the things that has stopped me from completing the implementation of mscorlib was some incorrectly resolved overloads. The last few commits will hopefully have helped. When I get time I intend to try and get a complete binding for mscorlib. 

How are you finding using the bridge code with Swift? If you have some  sample code it would make an interesting commit.

**Comment by Numpsy** [comment]
That would be useful, if rather large! (I've added the bindings for a few other mscorlib bits and pieces to my own project as it stands - easier with standalone things than adding to interfaces which are already partly there).

As far as swift goes it works pretty well, with an odd issue with casting and such. Saying that, I've done a bit of manual set up to use the ObjC frameworks from a Swift framework, which i'll mention in another issue.

**Comment by Numpsy** [comment]
As far as Swift and IEnumerable... goes, i'm playing with something like this:

```
extension System_Collections_ObjectModel_CollectionA1: Sequence {
    
    public func makeIterator() -> IEnumeratorIterator {

        let _enumerator = self.getEnumerator()
        return IEnumeratorIterator(_enumerator!)
    }
}

public struct IEnumeratorIterator: IteratorProtocol {
    let _enumerator: System_Collections_Generic_IEnumeratorA1Protocol

    public init(_ enumerable: System_Collections_Generic_IEnumeratorA1Protocol) {
        self._enumerator = enumerable
    }
    
    mutating public func next() -> System_Object? {
        
        let hmm = _enumerator.moveNext()
        
        if hmm {
            return self._enumerator.current
        } else {
            return nil
        }
    }
}


```

Which lets you use a for... loop directly over the managed collection, as well as possibly using other collections functions (although, a bit limited due to the lack of type information).

It's not looking quite as simple as the above example as System_Collections_Generic_IEnumeratorA1Protocol tends to be an instance of System_Collections_Generic_IEnumeratorA1 which doesn't implement moveNext, meaning a System_Collections_Generic_IEnumerator might be needed as well, but it still makes the calling code a bit neater than having to convert things to arrays first :-)

**Comment by KosmicTask** [comment]
Yes the complete binding would be large but the dynamic linker functions - dlopen() and dlsym() - only load executable code for symbols that are actually used. I had thought that a native Swift - .NET bridge would be a good idea but perhaps we can just add some Swift helpers. I have wanted to add enumerator support for ages but my usage case scenario involves tons of bindings so I need NSArray instances for that. I have to resort to bad tasting casts at times too. I find that the managed interfaces quite troublesome to deal with!

**Comment by KosmicTask** [comment]
I forgot to mention that the new thunk based property code is about 3x faster than using the method descriptor API. The actual thunking is way way faster than a method invoke but the Obj-C overhead is more dominant. The property thunk code is a bit of a mouth full for each property so I may well macro-ise it if the code looks solid.

**Comment by Numpsy** [comment]
I wondered about direct Swift bindings when falling over the issues with ordering of includes (missing forward declares etc), as Swift is closer to C# etc with less of those issues.
Swift might be better for handling .NET generics as well, though i'm not sure how pure swift classes would fit with Dubrovniks type handling (NSClassFromString not working with them unless they derive from an ObJC class)... getting a bit off topic there though!

**Comment by KosmicTask** [comment]
I agree. The heading ordering is a bit of a headache alright - I am not sure I have that one cracked for mscolrlib.dll yet. And yes generic handling might be easier. I don't have any real Swift experience. But certainly i have used Obj-C dynamic features a lot.

**Comment by Numpsy** [comment]
The bindings seem pretty solid now, so this actual bug could be closed (don't know if the thought about Sequences counts as interesting or useful enough to mention somwhere)

**Comment by KosmicTask** [comment]
Closing this for now. Re-raise the sequence issue if needs be.
