### ISSUE TITLE
DBManagedEnvironment::configureAssemblyRootPath

### ISSUE THREAD

**Issue by Numpsy** [ThesaurusSoftware/Dubrovnik#2]
Inside configureAssemblyRootPath, we have

```
const char *rootFolder = [monoAssemblyRootFolder fileSystemRepresentation];
const char *configFolder = [monoConfigFolder fileSystemRepresentation];
```

and i'm wondering if that should actually be

```
const char *rootFolder = [_monoAssemblyRootFolder fileSystemRepresentation];
const char *configFolder = [_monoConfigFolder fileSystemRepresentation];
```

?

While doing some testing I tried to set the config path to a folder under ~/Library, and that caused the Mono emulated registry bits to fail after trying to open "~/Library/application support/x/mono/4.5/../registry/localmachine".
I can fix it by expanding the paths myself, but it looks like the intention is for this to work as is?

**Comment by Thesaurus** [comment]
I think you are right there about that. The instance variables should be the receivers for -fileSystemRepresentation.

To be honest I don't know much about the managed config system. Personally I haven't hit any issues with it.

**Comment by Numpsy** [comment]
In this case I was attempting to change the place it loads the emulated Windows Registry from - by default it goes under </Library/Frameworks/Mono.framework/Versions/<version>/etc/mono/registry>, which isn't ideal. (the Mono installer doesn't even create the 'registry' folder, which causes errors when you try to use it).

Our config code will probably be changed to not use the registry at some point, but for now it's useful for testing at least.

**Comment by Numpsy** [comment]
oops, that should be /Library/Frameworks/Mono.framework/Versions/4.0.4/etc/mono/registry

**Comment by Thesaurus** [comment]
I have pushed a fix for this. Get back to me if woe prevails.
