### ISSUE TITLE
System_Delegate+mscorlib.h  registerUniversalDelegate no longer declared

### ISSUE THREAD

**Issue by PSFarrington** [ThesaurusSoftware/Dubrovnik#20]
We have just tried using the latest Dubrovnik code generator (we had been using 1719 ).
We had been calling System_Delegate.registerUniversalDelegate() during the initialisation of our process.
However, that function is not exposed in the latest version. Though it appears to be still present in the System_Delegate+mscorlib.m file.
Is there a way to perform that same functionality using the new version ? Could we just expose that function in the header file again ?

**Comment by Thesaurus** [comment]
I think that System_Delegate.registerUniversalDelegate() now gets called lazily in 
+ (instancetype)universalDelegateWithConstructedType:(System_Type *)delegateType block:(DBUniversalDelegateBlock)block

Just remove your call to System_Delegate.registerUniversalDelegate()  and see how you get on. Post again if you have issues.

Sorry about that : we sort of mutate the API for our own particular needs from yearly release to release and don’t worry too much about backwards compatibility.

**Comment by PSFarrington** [comment]
[Boldon James | Public]

Thanks.
I’d seen it was being invoked behind the scenes by those other constructors; and we do call those other constructors elsewhere in our code, so hopefully we’ll be ok. I’ll give it and go.
Regards
Paul

**Comment by Numpsy** [comment]
@PSFarrington is this sorted now?

**Comment by KosmicTask** [comment]
I think this should be fine now.

**Comment by PSFarrington** [comment]
[Boldon James | Public]

Yes. I removed that registerUniversalDelegate call, and the product has kept on working fine - we have been continuing to make use of delegate calls with no problems.
