### ISSUE TITLE
Support for universal mono builds

### ISSUE THREAD

**Issue by Numpsy** [ThesaurusSoftware/Dubrovnik#5]
So, we have an alpha release on Mono 4.3.2 for OSX, and it's a universal build rather than a 32bit build :-)

I tried building Dubrovnik against the universal framework rather than a local Mono64 one, and that seems to be working ok (though I did fall over https://bugzilla.xamarin.com/show_bug.cgi?id=39100 while trying, which needed working around).

Just wondering what the situation will be with supporting the universal framework 'officially' rather than the 'mono64' one? At this point, the project i'm working on may well end up targetting 4.3 both for 64bit support, and for smoe other fixes.

**Comment by Thesaurus** [comment]
It would be easier for everyone to use an official build rather than a private one. This is something I would like to get done sooner rather than later.

**Comment by Numpsy** [comment]
fwiw, I'm now building against the official 4.4.2 universal build, and it seems to be working fine for our requirements.

**Comment by Thesaurus** [comment]
> On 26 Aug 2016, at 11:44, Richard Webb notifications@github.com wrote:
> fwiw, I'm now building against the official 4.4.2 universal build, and it seems to be working fine for our requirements.

Thanks for that.

**Comment by Numpsy** [comment]
Looks like this is sorted now? :-)

**Comment by KosmicTask** [comment]
Yes. I used recent 4.8 release candidate.
Seems to work well.
