### ISSUE TITLE
System.IEquatable

### ISSUE THREAD

**Issue by Numpsy** [ThesaurusSoftware/Dubrovnik#6]
Hi,

I'm using Dubrovnik to generate some bindings for a lib that uses System.IEquatable, which currently seems to be missing from the mscorlib headers.

Any interest in a pull request to add a stub version, e.g. https://github.com/Numpsy/Dubrovnik/commit/74a7dc0b2bed66ac0e3258179aa5a4fce0a23089 ?

**Comment by KosmicTask** [comment]
Sure. Fire in the pull request.

Most of the recent development has been going into the BPUKM-1617 branch https://github.com/ThesaurusSoftware/Dubrovnik/tree/BPUKM-1617
This mainly makes improvements with regard to handling representations of managed interfaces, DateTime issues and generic list handling.

I am also about to attempt adding support for callback delegates.

**Comment by Numpsy** [comment]
I've been using that branch for a bit :-)

I'll actually have a few more requests incoming as well - need to add some thing for some new libs i'm trying to bind, and possibly have a code generator issue to look at.

**Comment by KosmicTask** [comment]
Glad to hear that you have been on the more recent branch!
I will help out where I can with other requests.
Some stuff is genuinely tricky to handle.
