### ISSUE TITLE
Ordering issues with headers generated by the code generator

### ISSUE THREAD

**Issue by Numpsy** [ThesaurusSoftware/Dubrovnik#9]
While generating some new class bindings, I fell over some ordering issues with managed classes/intefaces that refer to each other.

Say that I have some C# along the lines of

```
public interface SimpleInterfaceA
{
    void test(SimpleInterfaceB sb);
}

public interface SimpleInterfaceB
{
}

```

Then the code generator can generate things along the lines of

```
@class SimpleInterfaceTest_SimpleInterfaceA;
@class SimpleInterfaceTest_SimpleInterfaceB;
...
@protocol SimpleInterfaceTest_SimpleInterfaceA <SimpleInterfaceTest_SimpleInterfaceA_, System_Object>

-(void)test_withSb:(id<SimpleInterfaceTest_SimpleInterfaceB_>)p1;

@end
```

Which fails to compile because the protocol for SimpleInterfaceB hasn't been declared yet.
Possibly it should be forward declaring the protocols as well as the classes ?

**Comment by mugginsoft** [comment]
Yes. I reckon you need @protocol SimpleInterfaceTest_SimpleInterfaceA_; etc

Load up Dubrovnik.Tools.sln and see Net2ObjC.tt.
This template file generates the Obj-C source.
WriteInterfaceFilePreliminaries() generates the @Class predec for each class via a call to WriteClassPredeclaration(CodeFacet facet).

foreach (NamespaceFacet @namespace in AssemblyFacet.Namespaces)
	{
		// collect facets that render as Obj-C protocols
		facets.AddRange(@namespace.Interfaces);
foreach (CodeFacet facet in facets)
		{
			WriteClassPredeclaration(facet);
		}

**Comment by KosmicTask** [comment]
Oops. Fat fingered that last comment.

Yes. I reckon you need @protocol SimpleInterfaceTest_SimpleInterfaceA_; etc

Load up Dubrovnik.Tools.sln and see Net2ObjC.tt.
This template file generates the Obj-C source.
WriteInterfaceFilePreliminaries() generates the @Class predec for each class via a call to WriteClassPredeclaration(CodeFacet facet).

Add an extra for loop, something like:

```
foreach (NamespaceFacet @namespace in AssemblyFacet.Namespaces)
{
   // collect facets that render as Obj-C protocols
   facets.AddRange(@namespace.Interfaces);
   foreach (CodeFacet facet in facets)
   { 
      string classObjCType = facet.ObjCFacet.Type;
#>
    @protocol<#=classObjCType#>;
<#+
   }
}
```

**Comment by Numpsy** [comment]
Ok, I'll have a look (actually, still need to properly fix that other one with classes in the global namespace as well)

**Comment by Numpsy** [comment]
Right, finally getting some time to look at some things.

I guess that:

1) it's the name of the adoption protocol that needs declaring for parameter use rather than the implementation protocol?
2) this needs to pay attention to the type skipping options that have recently been added?

**Comment by Thesaurus** [comment]
I am working my way through this at the moment.
Hopefully it will all come out in the wash in the next few days.

Basically, the way I order the ObjC headers for an assembly is plain wrong.
By chance it has worked for me in my usage case bit it is not correct.

The type skipping options will enable us to skip given types.
I am using this to try and auto gen mscorlib in a manageable way - seems to be working out.
But this really highlights the header ordering issue.

I don’t much like the way I have adoption and implementation protocols but is was the only thing I could come up with that worked with explicit interface implementations.
We may be able to improve this in future.
 
When a ObjC type is returned from managed code it will use the adoption protocol.
Just cast it using the implementation protocol and it should work okay.
Klutzy I know.

The mostly recently updated code in BPUKM-1819 is not yet fit for purpose.
I develop on a Windows 10 VM to run the codegen and macOS 10.13 to run the unit tests.
So I have to push and pull a lot to keep the two in sync - which is not ideal I know as it can leave the repo in a non buildable state

Keep an eye on the repo and I will drop you a line when I think I have this sorted.
May be some time next week before I get time to hopefully finish this off.

**Comment by Numpsy** [comment]
>>>> Basically, the way I order the ObjC headers for an assembly is plain wrong.

I wondered about other possible issues (alphabetical includes etc), but it's been working pretty well for me overall.

>>>> The type skipping options will enable us to skip given types.

I was looking at that as it might be useful when creating the bindings for some large libs here (though i should have less issues with that when the bindings for the runtime libs are more complete).

The thing with the protocols is something else that is useable enough for what we're doing with it (the issues like the ones i mentinoed in #12 being potentially wierd at times but workable enough).

>>>>I develop on a Windows 10 VM to run the codegen and macOS 10.13 to run the unit tests.

Have you tried it in Visual Studio for Mac? It has some T4 template handling built in and there are TextTemplating packages on Nuget that seem to work on the Mac (the Reflector UI even seems to run, albeit not prettily)

**Comment by Thesaurus** [comment]
> Have you tried it in Visual Studio for Mac? It has some T4 template handling built in and there are TextTemplating packages on Nuget that seem to work on the Mac (the Reflector UI even seems to run, albeit not prettily)
> 
> 
I didn’t know that that the T4 template processing was available on the VS Mac now - will have to check that out.

I use build scripts in my windows VS production setup to automatically run the reflector and codegen to produce my ObjC bindings.
But it would be handy to be able to develop all of Dubrovnik on the macOS.

Last time I looked, opening a VS solution file on Monodevelop tending to mess it up.
I also couldn’t get post build scripts to place nicely together either.

Maybe time for another look see.

**Comment by Numpsy** [comment]
Handling of project files seems better now (using the MS build system and compiler helps I suppose), but there are still problems with post build steps (we have projects with post build steps that generate serialization assemblies which cause it to break, would be nice there if you could change the steps based on build the build configuration :-( ).

**Comment by Numpsy** [comment]
Can I ask about the current state of the branches?
We have a project that is currently using the 1718 branch from November, and it's getting time to look at an update. The update and extra bindings in 1819 branch would be useful, if that is in a testable state now?

Thanks.

**Comment by KosmicTask** [comment]
Hi

I am using the 1819 branch in our production code without any issues.
I didn’t get around to updating GitHub to point to the new branch just yet.

There is quite a lot of new stuff in there - the readme.md file hasn’t been updated yet.

There are very comprehensive bindings now for mscorlib - I use a filter to extract unwanted types.
Seems to work well and can be used on your own assemblies as well.

Looking at the commits is probably your best bet for now.

Still more work to be done and I might take a week sometime soon to blitz some more issues.

J

**Comment by Numpsy** [comment]
Ok, thanks, i'll take a look next week.

**Comment by Numpsy** [comment]
This can perhaps be closed now? Things seem in a better state with the current code generator.

**Comment by KosmicTask** [comment]
Yes. I am pretty sure this one is sorted.
